var foodJson = new Array();
foodJson.push({'label':'Dal','value':'Dal','calorie':'198','protein':'10','carbohydrate':'26','fat':'6.32'});
foodJson.push({'label':'Rice','value':'Rice','calorie':'204','protein':'4.2','carbohydrate':'44','fat':'0.4'});
foodJson.push({'label':'Chapati','value':'Chapati','calorie':'68','protein':'2.3','carbohydrate':'13','fat':'0.6'});
foodJson.push({'label':'Milk','value':'Milk','calorie':'122','protein':'8','carbohydrate':'12','fat':'5'});
foodJson.push({'label':'Tea','value':'Tea','calorie':'17','protein':'0.8','carbohydrate':'1.6','fat':'0.8'});
foodJson.push({'label':'Banana','value':'Banana','calorie':'121','protein':'1','carbohydrate':'31','fat':'0'});
foodJson.push({'label':'Chicken','value':'Chicken','calorie':'147','protein':'16','carbohydrate':'0','fat':'8'});
foodJson.push({'label':'Egg','value':'Egg','calorie':'74','protein':'6','carbohydrate':'.4','fat':'5'});
foodJson.push({'label':'Fish','value':'Fish','calorie':'127','protein':'26','carbohydrate':'0','fat':'1'});
foodJson.push({'label':'Mutter Paneer','value':'Mutter Paneer','calorie':'200','protein':'7','carbohydrate':'8','fat':'15'});
foodJson.push({'label':'Samosa','value':'Samosa','calorie':'190','protein':'4','carbohydrate':'21','fat':'10'});
foodJson.push({'label':'Gulabjamun','value':'Gulabjamun','calorie':'215','protein':'4','carbohydrate':'42','fat':'3'});